when:
  - event: tag

steps:
  release-build:
    image: golang:1.26
    commands:
      - mkdir -p dist
      - GOOS=darwin  GOARCH=amd64 go build -ldflags "-X main.Version=${CI_COMMIT_TAG}" -o dist/cerveau-darwin-amd64  ./cmd/cerveau/
      - GOOS=darwin  GOARCH=arm64 go build -ldflags "-X main.Version=${CI_COMMIT_TAG}" -o dist/cerveau-darwin-arm64  ./cmd/cerveau/
      - GOOS=linux   GOARCH=amd64 go build -ldflags "-X main.Version=${CI_COMMIT_TAG}" -o dist/cerveau-linux-amd64   ./cmd/cerveau/
      - GOOS=linux   GOARCH=arm64 go build -ldflags "-X main.Version=${CI_COMMIT_TAG}" -o dist/cerveau-linux-arm64   ./cmd/cerveau/

  release-upload:
    image: woodpeckerci/plugin-s3
    settings:
      endpoint:
        from_secret: artifact_endpoint
      region:
        from_secret: artifact_region
      bucket:
        from_secret: artifact_bucket
      access_key:
        from_secret: artifact_access_key
      secret_key:
        from_secret: artifact_secret_key
      path_style: true
      acl: public-read
      source: dist/*
      target: /cerveau/${CI_COMMIT_TAG}/
